# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

description: Experiment "finetune_phi4_mi300x"

target:
  service: sing
  name: whitney14
  workspace_name: aifrontiers_ws

environment:
  image: rocm6.3.4-pytorch2.7.1-deepspeed0.17.1-flashattn2.8.0.post2-vllm0.9.0.dev:20250702
  registry: aifrontiers.azurecr.io
  setup:
    - set -e -o xtrace
    - pip install -e .[rl]

storage:
  aifshared:
    storage_account_name: aifshared
    container_name: data
  output:
    storage_account_name: aifshared
    container_name: amulet

code:
  # Copy this YAML to `phyagi-experiments` repository for changes,
  # and remember to change the `local_dir` to your `phyagi-sdk` repository path
  local_dir: <PATH/TO/phyagi-sdk>

jobs:
  - name: p1_phi4_ds_sft
    sku: 1xG8-MI300X-IB-xGMI
    sla_tier: premium
    priority: medium
    mpi: True
    process_count_per_node: 8
    command:
      - cd scripts/train
      - python ds_train.py configs/phi4/ds_sft_phi4.yaml --model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-base/last@0010714_pp0/mixformer-sequential --model.architecture.norm.norm_cls rms --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_API_KEY: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers
  - name: p1_phi4_pl_sft
    sku: 1xG8-MI300X-IB-xGMI
    sla_tier: premium
    priority: medium
    mpi: True
    process_count_per_node: 8
    command:
      - cd scripts/train
      - python pl_train.py configs/phi4/pl_sft_phi4.yaml --model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-base/last@0010714_pp0/mixformer-sequential --model.architecture.norm.norm_cls rms --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_API_KEY: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers