# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

description: Experiment "finetune_phi4"

target:
  service: sing
  name: baltic08
  workspace_name: aifrontiers_ws

environment:
  image: nvidia25.03-pytorch2.7.1-te2.4-deepspeed0.17.1-flashattn2.8.0.post2-vllm0.9.1:20250702
  registry: aifrontiers.azurecr.io
  setup:
    - set -e -o xtrace
    - pip install -e .[rl]

storage:
  aifshared:
    storage_account_name: aifshared
    container_name: data
  output:
    storage_account_name: aifshared
    container_name: amulet

code:
  # Copy this YAML to `phyagi-experiments` repository for changes,
  # and remember to change the `local_dir` to your `phyagi-sdk` repository path
  local_dir: <PATH/TO/phyagi-sdk>

jobs:
  - name: p1_phi4_ds_sft_combined2_32k
    sku: 8xG8-H100-IB
    sla_tier: premium
    priority: medium
    mpi: True
    process_count_per_node: 8
    command:
      - cd scripts/train
      - python ds_train.py configs/phi4/ds_sft_phi4_combined2_32k.yaml --model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-base/last_0010714_pp0/mixformer-sequential-32k --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_API_KEY: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers
  - name: p1_phi4_ds_sft_openthoughts_csm
    sku: 1xG8-H100-IB
    sla_tier: premium
    priority: medium
    mpi: True
    process_count_per_node: 8
    command:
      - cd scripts/train
      - python ds_train.py configs/phi4/ds_sft_phi4_openthoughts.yaml --model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-base/last_0010714_pp0/mixformer-sequential --model.cross_sample_masking true --model.cross_sample_token_id 100257 --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_API_KEY: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers
  - name: p1_phi4_ds_sft_openthoughts
    sku: 1xG8-H100-IB
    sla_tier: premium
    priority: medium
    mpi: True
    process_count_per_node: 8
    command:
      - cd scripts/train
      - python ds_train.py configs/phi4/ds_sft_phi4_openthoughts.yaml --model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-base/last_0010714_pp0/mixformer-sequential --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_API_KEY: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers
  - name: p1_phi4_ds_sft
    sku: 1xG8-H100-IB
    sla_tier: premium
    priority: medium
    mpi: True
    process_count_per_node: 8
    command:
      - cd scripts/train
      - python ds_train.py configs/phi4/ds_sft_phi4.yaml --model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-base/last@0010714_pp0/mixformer-sequential --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_API_KEY: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers
  - name: p1_phi4_pl_sft
    sku: 1xG8-H100-IB
    sla_tier: premium
    priority: medium
    mpi: True
    process_count_per_node: 8
    command:
      - cd scripts/train
      - python pl_train.py configs/phi4/pl_sft_phi4.yaml --model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-base/last@0010714_pp0/mixformer-sequential --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_API_KEY: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers
  - name: p1_phi4_hf_sft
    sku: 1xG8-H100-IB
    sla_tier: premium
    priority: medium
    mpi: True
    process_count_per_node: 8
    command:
      - cd scripts/tune
      - python hf_sft_tune.py configs/phi4/hf_sft_phi4.yaml --model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-base/last@0010714_pp0/hf --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_API_KEY: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers
  - name: p1_phi4_hf_dpo
    sku: 1xG8-H100-IB
    sla_tier: premium
    priority: medium
    mpi: True
    process_count_per_node: 8
    command:
      - cd scripts/tune
      - python hf_dpo_tune.py configs/phi4/hf_dpo_phi4.yaml --model.pretrained_model_name_or_path /mnt/aifshared/post_train_models/phi-4-sft-phyagi --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_API_KEY: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers
  - name: p1_phi4_ray_grpo
    sku: 1xG8-H100-IB
    sla_tier: premium
    priority: medium
    mpi: False
    process_count_per_node: 1
    command:
      - cd scripts/tune
      - phyagi-cli start-ray-cluster
      - RAY_DEDUP_LOGS=0 python ray_grpo_tune.py configs/phi4/ray_grpo_phi4.yaml --tuning_args.n_nodes $$WORLD_SIZE --tuning_args.actor.model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-mf --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_TOKEN: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers
  - name: p1_phi4_ray_grpo_64k
    sku: 2xG8-H100-IB
    sla_tier: premium
    priority: medium
    mpi: False
    process_count_per_node: 1
    command:
      - cd scripts/tune
      - phyagi-cli start-ray-cluster
      - RAY_DEDUP_LOGS=0 python ray_grpo_tune.py configs/phi4/ray_grpo_phi4_64k.yaml --tuning_args.n_nodes $$WORLD_SIZE --tuning_args.actor.model.pretrained_model_name_or_path /mnt/aifshared/phi4checkpoints/phi-4-mf --output_dir $$AMLT_OUTPUT_DIR
    submit_args:
      env:
        WANDB_TOKEN: local-caf46ffffc84feab44e6da3913e16b683be41c53
        WANDB_HOST: https://microsoft-research.wandb.io
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d4fe558f-6660-4fe7-99ec-ae4716b5e03f/resourceGroups/aifrontiers/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aifrontiers