data_root: ${oc.env:DATA_ROOT, "/mnt/aifshared"}
output_root: ${oc.env:OUTPUT_ROOT, "~/phyagi_results"}
output_dir: ${output_root}/hf_sft
dataset:
  path: json
  data_files:
    - <path-to-jsonl-file>
model:
  pretrained_model_name_or_path: microsoft/phi-1
  torch_dtype: fp16
tokenizer:
  pretrained_tokenizer_name_or_path: microsoft/phi-1
  pad_token: <|endoftext|>
tuning_args:
  dataset_text_field: text
  max_seq_length: 512
  packing: false
  num_of_sequences: 1024
  chars_per_token: 3.6
  use_liger: false
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  max_steps: 10
  save_steps: 10
  learning_rate: 1.41e-5
  logging_steps: 1
  seed: 42
  fp16: True
  ddp_find_unused_parameters: false
peft_config:
  r: 64
  lora_alpha: 16
  bias: none
  task_type: CAUSAL_LM
  target_modules:
    - Wqkv
    - out_proj
    - fc1
    - fc2
