# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# DOCKER_BUILDKIT=1 docker buildx build --platform linux/x86_64 -t "aifrontiers.azurecr.io/oldrlimage_azureml_fadb9edd8b6a6d002c8067c65607e0a1:1" -f Dockerfile.oldrl ./docker_context/ --progress=plain

# Arguments supplied by running script
ARG BASE_IMAGE="aifrontiers.azurecr.io/azureml/azureml_fadb9edd8b6a6d002c8067c65607e0a1:1"

# Creates variables from arguments
FROM --platform=linux/amd64 $BASE_IMAGE AS base

# Defines the base image
FROM base
ENV DEBIAN_FRONTEND=noninteractive

# Install Verl AIF Deps
RUN pip install math-verify[antlr4-9-3]
RUN pip install vllm==0.8.1
RUN pip install tensordict==0.6.2
RUN pip install transformers==4.47.1