data_root: ${oc.env:DATA_ROOT, "/mnt/aifshared"}
output_root: ${oc.env:OUTPUT_ROOT, "~/phyagi_results"}
output_dir: ${output_root}/ds_sft_qwen2.5-7b_32k
dataset:
  - cache_dir: ${data_root}/post_train_data/final_v5/packed_16384/16k_data_20/
    seq_len: 32768
    weight: 1.0
  - cache_dir: ${data_root}/post_train_data/phoenix_sft_4k_ver13_16384/
    seq_len: 32768
    weight: 1.0
dataset_concat: random
dataset_provider: lm
model:
  pretrained_model_name_or_path: <pretrained_model_name_or_path>
  gradient_checkpointing: true
  n_positions: 32768
  architecture:
    mixer:
      rotary_base: 500000
    loss:
      loss_cls: causal_lm
      flash_cross_entropy_loss: true
      inplace_backward: true
training_args:
  ds_config:
    bf16:
      enabled: true
    data_types:
      grad_accum_dtype: fp32
    optimizer:
      type: AdamW
      params:
        lr: 1.0e-6
        betas:
        - 0.8
        - 0.95
        eps: 1.0e-8
        weight_decay: 0.0
    scheduler:
      type: WarmupDecayLR
      params:
        warmup_min_lr: 1.0e-7
        warmup_max_lr: 1.0e-6
        warmup_type: linear
        warmup_num_steps: 450
    zero_optimization:
      stage: 3
      offload_param:
        device: cpu
        pin_memory: true
        max_in_cpu: 1e12
      offload_optimizer:
        device: cpu
        pin_memory: true
        ratio: 0.99
      overlap_comm: true
      sub_group_size: 1e9
      contiguous_gradients: true
      stage3_max_live_parameters: 1e8
      stage3_max_reuse_distance: 1e8
      stage3_gather_16bit_weights_on_model_save: true
    gradient_clipping: 1.0
    steps_per_print: 10
    train_batch_size: 64
    train_micro_batch_size_per_gpu: 1
    wall_clock_breakdown: false
    zero_allow_untested_optimizer: true
  max_steps: 2385 # 5B tokens (1 epoch)
  logging_steps: 10
  save_steps: 100
  save_final_checkpoint: true
  load_checkpoint_num_tries: 3
  seed: 42
  timeout: 900
  eval_steps: 999999
  pipe_parallel_size: 1
  dataloader_shuffle: true
  dataloader_num_workers: 1
  dataloader_prefetch_factor: 512
  wandb: true
