name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "phyagi/**"
      - "tests/**"

jobs:
  unit-test:
    name: Runs unit tests with `pytest`
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
        - name: Pulls the repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Sets up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Installs dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install torch==2.6.0
            python -m pip install .
        - name: Runs unit tests
          run: |
            python -m pytest tests
